version: '3.8'

services:
  na3-wallet-service:
    image: na3-wallet-service
    restart: always
    build: .
    ports:
      - '127.0.0.1:${PORT:-3696}:${PORT:-3696}'
      - '127.0.0.1:${GRPC_PORT:-3094}:${GRPC_PORT:-3094}'
    volumes:
      - ./.env:/usr/src/app/.env
      - ../na3-interface:/usr/src/na3-interface # Need clone na3-interface source to inside na3-wallet-service
    networks:
      - na3_network

networks:
  na3_network:
    external: true
